# Generated by Django 3.0.8 on 2020-07-17 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='choice_text',
            new_name='option_text',
        ),
    ]
