# Generated by Django 3.0.8 on 2020-07-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0005_ballot_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='option_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
