# Generated by Django 3.0.8 on 2020-07-25 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0006_auto_20200725_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_number',
            field=models.IntegerField(null=True),
        ),
    ]
