# Generated by Django 3.0.8 on 2020-07-25 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0007_auto_20200725_1626'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='voter_id',
            new_name='token',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='date_created',
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ballot.Voter')),
            ],
        ),
    ]
