# Generated by Django 3.0.8 on 2020-07-25 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ballot', '0009_vote_ballot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ballot',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
